require 'opal'
require 'fron/js/scroll_into_view_if_needed'
require 'fron/core_ext'
require 'fron/dom'
require 'fron/core'
require 'fron/request'
require 'fron/storage'
require 'fron/utils/render_proc'
