require 'opal'
require './fron/dom'
require './fron/request'
require './fron/storage'

require './core/logger'
require './core/component'
require './core/adapters/rails'
require './core/adapters/local-storage'
require './core/configuration'
require './core/eventable'
require './core/model'
require './core/router'
require './core/controller'
require './core/application'
