AllCops:
  Exclude:
    - website/**/*

VariableName:
  EnforcedStyle: snake_case

MethodName:
  EnforcedStyle: snake_case

HandleExceptions:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

TrivialAccessors:
  Enabled: false

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

RegexpLiteral:
  Enabled: false

AbcSize:
  Enabled: false

PerceivedComplexity:
  Enabled: false

EmptyElse:
  Enabled: false

PredicateName:
  Enabled: false

BlockDelimiters:
  Enabled: false

CommandLiteral:
  Enabled: false
