AllCops:
  Exclude:
    - vendor/**/*

VariableName:
  EnforcedStyle: snake_case

MethodName:
  EnforcedStyle: snake_case

HandleExceptions:
  Enabled: false

Blocks:
  Enabled: true

SingleSpaceBeforeFirstArg:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

Blocks:
  Enabled: false

TrivialAccessors:
  Enabled: false

ClassLength:
  Enabled: false

UnneededPercentX:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

RegexpLiteral:
  Enabled: false

AbcSize:
  Enabled: false

PerceivedComplexity:
  Enabled: false

EmptyElse:
  Enabled: false

PredicateName:
  Enabled: false
